# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
library(logger)
library(config)

# test environment
config <- config::get(file = "config/config.yml")


log_info("authenticating to S3...")

b <- board_s3(
  bucket = "model-artifacts-dump",
  region = structure("eu-south-1",
                     tags = list(type = "scalar")),
  access_key = config$aws$aws_access_key,
  secret_access_key = config$aws$aws_secret_access_key
  )

v <- vetiver_pin_read(b, "model_example", version = "20221104T150445Z-9ca24")



polished::polished_config(
  api_key = config$auth$auth_key,
  app_name = config$auth$app_name
)



cors = function(req, res) {
  res$setHeader("Access-Control-Allow-Credentials", "true")
  res$setHeader("Access-Control-Allow-Origin", "http://localhost:8000")

  if (req$REQUEST_METHOD == "OPTIONS") {
    res$setHeader("Access-Control-Allow-Methods","*")
    res$setHeader("Access-Control-Allow-Headers", req$HTTP_ACCESS_CONTROL_REQUEST_HEADERS)
    res$status <- 200
    return(list())
  } else {
    plumber::forward()
  }
}


##' @filter auth
# polished::auth_filter()


# do not actually show this in the post
#' @post /hi
#'
#' @serializer unboxedJSON
#'
function(req, res) {

  return(req$polished_session)
}


#* Log some information about the incoming request
#* @filter logger
function(req){
  log_info(
    req$REQUEST_METHOD, req$PATH_INFO, "-",
    req$HTTP_USER_AGENT, "@", req$REMOTE_ADDR)
  plumber::forward()
}



#* @plumber
function(pr) {
    pr %>%
    vetiver_api(v, debug = TRUE)
}
